language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
- pip install python-coveralls
env:
- SETTINGS=config.TestConfig
script: 
- source ./environment_test.sh
- py.test --cov application tests/ --cov-report=term --cov-report=html
after_success:
  - coveralls --ignore-errors
deploy:
  provider: heroku
  api_key:
    secure: LWDLbZ3fXk1jzWrfWdpA6Gj87Jd+jlfKw6PZ3AFjcvJEhImcB70Mzk4pBFtoMTYlrNg5CJM8SFrsos/L4VrRGWjS+Hrvvo30CzwlO8Bd5JgtVD3auGNqls6NPJEuiw4R2il3e9w7CJtN6Fq5C48NzfSU/ofOSyrTn7OCVREqXWs=
  app: lr-casework-frontend
  on:
    repo: LandRegistry/casework-frontend
    branch: master
  run: "python manage.py db upgrade"
