language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
script: py.test
deploy:
  provider: heroku
  api_key:
    secure: f08NDNBSVc/Stsq6a2JTCZUv8HoOqP9wlsV3xYjBcvI8ABs+HW7f4tzatI718JoxN9Ck1QsKzSHXbqA1adygAd+V4iMKEOfA0/90cCdVKJdIWYnmT9KNw8AUuuux3GyHdkGSPKzQAWEf0D09moCOVZB40nGp0zsLHGaOS31oTAc=
  app: lr-casework-frontend
  on:
    repo: LandRegistry/casework-frontend
