"""empty message

Revision ID: 143db59ade88
Revises: 5542907a3042
Create Date: 2014-08-13 14:42:51.015385

"""

# revision identifiers, used by Alembic.
revision = '143db59ade88'
down_revision = '5542907a3042'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_number', sa.String(length=64), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('application_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('applications')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.INTEGER(), server_default="nextval('applications_id_seq'::regclass)", nullable=False),
    sa.Column('title_number', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('application_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'applications_pkey')
    )
    op.drop_table('casework')
    ### end Alembic commands ###
