"""empty message

Revision ID: 15685a70ccc9
Revises: 4a0b77571480
Create Date: 2014-08-12 10:47:39.556412

"""

# revision identifiers, used by Alembic.
revision = '15685a70ccc9'
down_revision = '4a0b77571480'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_number', sa.String(length=64), nullable=False),
    sa.Column('application_type', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    ### end Alembic commands ###
