"""empty message

Revision ID: 2dbdc40fee81
Revises: 7bf4fc96689
Create Date: 2014-11-17 10:28:35.749745

"""

# revision identifiers, used by Alembic.
revision = '2dbdc40fee81'
down_revision = '7bf4fc96689'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
