"""empty message

Revision ID: 2f431e7af4b8
Revises: None
Create Date: 2014-07-21 14:14:12.954693

"""

# revision identifiers, used by Alembic.
revision = '2f431e7af4b8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('title_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_number', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title_numbers')
    ### end Alembic commands ###
