"""empty message

Revision ID: 5542907a3042
Revises: 15685a70ccc9
Create Date: 2014-08-12 16:50:15.769317

"""

# revision identifiers, used by Alembic.
revision = '5542907a3042'
down_revision = '15685a70ccc9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_number', sa.String(length=64), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('application_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checks')
    ### end Alembic commands ###
