"""empty message

Revision ID: 7bf4fc96689
Revises: 371c2c5de85
Create Date: 2014-09-23 09:44:09.825186

"""

# revision identifiers, used by Alembic.
revision = '7bf4fc96689'
down_revision = '371c2c5de85'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checks')
    op.drop_table('casework')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casework',
    sa.Column('id', sa.INTEGER(), server_default="nextval('casework_id_seq'::regclass)", nullable=False),
    sa.Column('title_number', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('application_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'casework_pkey')
    )
    op.create_table('checks',
    sa.Column('id', sa.INTEGER(), server_default="nextval('checks_id_seq'::regclass)", nullable=False),
    sa.Column('title_number', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('application_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'checks_pkey')
    )
    ### end Alembic commands ###
